name: push
on: [pull_request]
jobs:
  CI:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Cache
    - uses: actions/setup-node@v3
      with:
        node-version: '14'
        cache: 'pnpm'
    - name: Install modules
      run: pnpm ci
    - name: Run unit tests with jest
      run: pnpm run test
    - name: Run eslint (only warnings)
      run: pnpm run lint
  label:

  runs-on: ubuntu-latest
  permissions:
    contents: read
    pull-requests: write

  steps:
  - uses: actions/labeler@v4
    with:
      repo-token: "${{ secrets.GITHUB_TOKEN }}"
